### ISSUE TITLE
data-trigger ?

### ISSUE THREAD

**Issue by londoh** [sebastiansulinski/cascading-dropdown#1]
Hi
just trying out your plugin (with some hope and optimism!), and notice in the docs it says:

> All selects except the first one are also required to have the following data-\* attributes:

```
data-id : the id of the element corresponds to the data-trigger of the previous element
```

But I dont find data-trigger mentioned anywhere else, including in your demos
whereas data-id appears to reference data-target of prev el

is this an error in docs or my understanding?

regards

l.

**Comment by sebastiansulinski** [comment]
Hi @londoh - you're right - it should be `data-target` - thanks for pointing this out. I'll update the docs in a moment.
