### ISSUE TITLE
Show the result of combinations

### ISSUE THREAD

**Issue by santoshmaharjan** [sebastiansulinski/cascading-dropdown#2]
Hi Sebastian,

How do I show the result of the individual combinations using ajax. For example:
Jeans > Lewis > Black > 7 --> $50
Shoes > Vans > Black > 8 --> $45 etc
I want to show the result in the place where it says "To see results please make your selection using menus above."

Thanks for the wonderful script.

**Comment by sebastiansulinski** [comment]
Hi @santoshmaharjan,

You'd have to fetch them from within the file that you make the call to based on the parameters you're sending. Examples make calls to the static `.json` files `/data/colour.json?category=2&make=1`, but you can make it to say php page, which takes arguments `category=2&make=1` and based on that selection fetches the records, formats them in the correct format  and returns as a `replacement` json index back to javascript to replace the content. I hope this makes sense.

**Comment by santoshmaharjan** [comment]
Hi Sebastian,
I am a noob. Can you please code an example for me.

**Comment by sebastiansulinski** [comment]
Change `data-url` attribute on each select to the php or any other server side coded location, which will take arguments such as `category` etc. Then based on these arguments full the records, format your html output and return it back in the json format. The structure of the json output you'll find with the exercise files under `data` directory.

**Comment by santoshmaharjan** [comment]
I will try. Thanks a lot. Just in case I am not able to, can you do it for me at cost?

**Comment by sebastiansulinski** [comment]
Possibly, but it depends on when you need it by.

**Comment by santoshmaharjan** [comment]
As soon as possible. Please quote the rate the mode of payment.

**Comment by sebastiansulinski** [comment]
Drop me an email vila the enquiry form and we can continue from there. https://ssdtutorials.com/contact
