### ISSUE TITLE
Hey nice dropdown but ...

### ISSUE THREAD

**Issue by cvelele** [sebastiansulinski/cascading-dropdown#3]
how to change than t-shirts is only adidas and nike, and shoes just lewis and so one. Than if select adidas show only red and black, and if choose nike red, black and blue. So not to be same choice what ever i previously select.

What ever combination choose always the same price. How to specify price for Shoes->Adidas->White->Size 8 and how for Hats->Vans->Black->Size 7 ?

And at the end how to show picture of a product next to the price?

My knowledge is intermediate, so maybe is easy but not for me.

thanks

**Comment by sebastiansulinski** [comment]
You have to do it on the server side - this is just a plugin and I don't provide support for custom request I'm afraid - sorry about that.
