### ISSUE TITLE
nice dropdown with require.js

### ISSUE THREAD

**Issue by ivanpolak** [sebastiansulinski/cascading-dropdown#4]
there is a problem with require.js library:

Uncaught Error: Mismatched anonymous define() module: function (a0) {
            return (factory(a0));
        }
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:168)
    at intakeDefines (require.js:1254)
    at require.js:1452

it is posiible to use this very nice plugin with require.js library (http://requirejs.org/) ?

thanks

**Comment by sebastiansulinski** [comment]
Can you just confirm you have `jquery` as a dependency for this plugin set in your config?
I've updated the plugin's module block for amd - can you try latest version (v1.4.3) and see if you still experience the problem?

**Comment by ivanpolak** [comment]
thanks! everything is OK. thanks!
